// AUTO-GENERATED by scripts/generate-lessons.mjs at build time.
// Source: ../lessons/*.yml. Do not edit by hand.

import type { Lesson } from "./lessons";

export const LESSONS: Lesson[] = [
  {
    "id": "m2-primera-conversacion",
    "module_number": 2,
    "language": "en",
    "title": "Your first conversation",
    "subtitle": "Talk to Claude with context, goal, and tone",
    "description": "Break the ice with Claude Code and get a first win in less than ten minutes. The whole conversation runs on the shared sandbox \"Empresa Prueba\", a fictional company with eight departments living in ~/empresa-prueba.\n",
    "estimated_minutes": 7,
    "sandbox": "empresa-prueba",
    "mental_model": "Don't talk to Claude like you talk to a search engine. Talk to it like you'd talk to a sharp intern who just walked in. Context, goal, tone.\n",
    "preconditions": {
      "working_directory": "/home/learner/empresa-prueba",
      "claude_running": true
    },
    "steps": [
      {
        "id": "leer-departamento",
        "title": "Ask Claude to read a department",
        "body": "Claude Code is in front of you, already open in the Empresa Prueba folder. First trick: when you ask for something, tell it WHERE to look and WHAT you want back. Here you ask it to read the 01-ventas folder and answer in three sentences.\n",
        "prompt": "Read the 01-ventas folder and tell me in three sentences\nwhat this department does.\n",
        "hint": "Trick: \"three sentences\" is a clear goal. Without that hint, Claude can drop two paragraphs on you. With it, it adjusts.\n",
        "xp": 10,
        "success": {
          "type": "claude_tool_call",
          "match": {
            "tool": "Read",
            "path_regex": "01-ventas"
          }
        },
        "success_title": "Nice! Claude read the department",
        "success_sub": "You earned 10 XP. Move to step 2 and learn how to correct it."
      },
      {
        "id": "corregir-sobre-la-marcha",
        "title": "Now ask for shorter",
        "body": "If the answer is too long or the tone isn't right, you don't have to start over. You tell Claude and it adjusts on the same conversation.\n",
        "prompt": "too long, make it two sentences and an informal tone\n",
        "hint": "Trick: the more specific the correction, the better. \"Shorter\" works. \"Two sentences, informal tone, no bullet points\" works even better.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)(two\\s+sentences|shorter|informal)"
        },
        "success_title": "Nice! You corrected without restarting",
        "success_sub": "You earned 10 XP. Move to step 3 to ask for something more ambitious."
      },
      {
        "id": "pedir-algo-ambicioso",
        "title": "Ask for something more ambitious",
        "body": "Claude isn't just for short questions. Ask for a real deliverable: a one-page summary of the department's status. You'll see it open several files in a row to compose the answer.\n",
        "prompt": "Prepare a one-page summary of the sales department's\nstatus. Pipeline, quarterly priorities, and two risks.\n",
        "hint": "Trick: when you ask for something big, tell it the structure you want. \"Pipeline, priorities, risks\" gives Claude the skeleton and stops it from inventing one.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)(summary|status).{0,40}(sales|department)"
        },
        "success_title": "Nice! You asked for a real deliverable",
        "success_sub": "You earned 10 XP. Last step: see what happens when info is missing."
      },
      {
        "id": "pregunta-sin-datos",
        "title": "Ask for something Claude CAN'T know",
        "body": "One of the most valuable things about Claude Code is that when it doesn't have the data, it says so. It doesn't make things up. Let's trigger that case on purpose so you see it.\n",
        "prompt": "how many customers do we have in Madrid?\n",
        "hint": "Trick: if Claude answers with a made-up number, stop it and say \"don't make things up, tell me what you'd need to know this\". That trains the habit of not accepting unsourced data.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)(how\\s+many|customers).{0,40}madrid"
        },
        "success_title": "Nice! You just learned how to trust Claude",
        "success_sub": "You earned 10 XP. You've finished your first conversation."
      }
    ],
    "on_complete": {
      "total_xp": 40,
      "takeaways": [
        "Talk to Claude with context, goal, and tone.",
        "Correct on the fly without starting over.",
        "Claude tells you when it lacks data, it doesn't invent."
      ],
      "next_module": "m3-organizar-cabeza",
      "trigger_signup": true
    }
  },
  {
    "id": "m2-primera-conversacion",
    "module_number": 2,
    "language": "es",
    "title": "Tu primera conversacion",
    "subtitle": "Hablar a Claude con contexto, objetivo y tono",
    "description": "Romper el hielo con Claude Code y tener una primera victoria en menos de diez minutos. La conversacion entera transcurre sobre el sandbox compartido \"Empresa Prueba\", una empresa ficticia con ocho departamentos en ~/empresa-prueba.\n",
    "estimated_minutes": 7,
    "sandbox": "empresa-prueba",
    "mental_model": "No hables con Claude como con un buscador. Hablale como a un becario listo que acaba de entrar. Contexto, objetivo, tono.\n",
    "preconditions": {
      "working_directory": "/home/learner/empresa-prueba",
      "claude_running": true
    },
    "steps": [
      {
        "id": "leer-departamento",
        "title": "Pidele a Claude que lea un departamento",
        "body": "Claude Code esta delante de ti, ya abierto en la carpeta de Empresa Prueba. Primer truco: cuando le pides algo, dile DONDE mirar y QUE quieres como respuesta. Aqui le pides que lea la carpeta 01-ventas y te responda en tres frases.\n",
        "prompt": "Lee la carpeta 01-ventas y dime en tres frases que hace\neste departamento.\n",
        "hint": "Truco: \"tres frases\" es un objetivo claro. Sin esa pista, Claude te puede soltar dos parrafos. Con ella, te ajusta.\n",
        "xp": 10,
        "success": {
          "type": "claude_tool_call",
          "match": {
            "tool": "Read",
            "path_regex": "01-ventas"
          }
        },
        "success_title": "¡Bien! Claude ha leido el departamento",
        "success_sub": "Ganas 10 XP. Sigue con el paso 2 para aprender a corregirle."
      },
      {
        "id": "corregir-sobre-la-marcha",
        "title": "Ahora pide que sea mas corto",
        "body": "Si la respuesta es larga o el tono no te convence, no hace falta empezar de cero. Se lo dices y lo ajusta sobre la misma conversacion.\n",
        "prompt": "demasiado largo, hazlo en dos frases y con tono informal\n",
        "hint": "Truco: cuanto mas especifica sea la correccion, mejor. \"Mas corto\" funciona. \"Dos frases, tono informal, sin listas\" funciona todavia mejor.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)(dos\\s+frases|mas\\s+corto|informal)"
        },
        "success_title": "¡Bien! Le has corregido sin reiniciar",
        "success_sub": "Ganas 10 XP. Sigue con el paso 3 para pedir algo mas ambicioso."
      },
      {
        "id": "pedir-algo-ambicioso",
        "title": "Pidele algo mas ambicioso",
        "body": "Claude no es solo para preguntas cortas. Pidele un entregable real: un resumen de una pagina del estado del departamento. Vas a ver como abre varios archivos seguidos para componer la respuesta.\n",
        "prompt": "preparame un resumen de una pagina del estado del\ndepartamento de ventas. Pipeline, prioridades del trimestre\ny dos riesgos.\n",
        "hint": "Truco: cuando pides algo grande, di que estructura quieres. \"Pipeline, prioridades, riesgos\" le da el esqueleto y evita que se invente uno.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)(resumen|estado).{0,40}(ventas|departamento)"
        },
        "success_title": "¡Bien! Has pedido un entregable de verdad",
        "success_sub": "Ganas 10 XP. Ultimo paso: ver que pasa cuando le falta info."
      },
      {
        "id": "pregunta-sin-datos",
        "title": "Pidele algo que NO puede saber",
        "body": "Una de las cosas mas valiosas de Claude Code es que cuando no tiene los datos, te lo dice. No inventa. Vamos a provocar ese caso a proposito para que lo veas.\n",
        "prompt": "cuantos clientes tenemos en Madrid?\n",
        "hint": "Truco: si Claude responde con un numero inventado, paralo y pidele \"no inventes, dime que te falta para saberlo\". Asi entrenas el habito de no aceptar datos sin fuente.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)(cuantos|clientes).{0,40}madrid"
        },
        "success_title": "¡Bien! Acabas de aprender a fiarte de Claude",
        "success_sub": "Ganas 10 XP. Has terminado tu primera conversacion."
      }
    ],
    "on_complete": {
      "total_xp": 40,
      "takeaways": [
        "Hablar a Claude con contexto, objetivo y tono.",
        "Corregir sobre la marcha sin empezar de cero.",
        "Claude te avisa cuando no tiene datos, no inventa."
      ],
      "next_module": "m3-organizar-cabeza",
      "trigger_signup": true
    }
  },
  {
    "id": "m3-organizar-cabeza",
    "module_number": 3,
    "language": "en",
    "title": "Organize your head",
    "subtitle": "A folder for your work and a CLAUDE.md file that says who you are",
    "description": "Create the mi-trabajo folder inside Empresa Prueba with four subfolders (people, projects, companies, archive) and a CLAUDE.md file at the root that Claude Code reads automatically every time you open a conversation in that folder.\n",
    "estimated_minutes": 8,
    "sandbox": "empresa-prueba",
    "mental_model": "Claude is the new chief of staff. Before asking for anything, you leave a folder of your stuff on the desk plus a sheet that says \"this is me\". From there it works on its own.\n",
    "preconditions": {
      "working_directory": "/home/learner/empresa-prueba",
      "claude_running": true
    },
    "steps": [
      {
        "id": "crear-carpeta-raiz",
        "title": "Create your work folder",
        "body": "Anything you put in here, Claude can see. Anything outside, doesn't exist for it. We start with a folder called mi-trabajo at the root of Empresa Prueba.\n",
        "prompt": "create a folder called mi-trabajo at the root\n",
        "hint": "Trick: asking in plain language is enough. Claude knows how to translate it into a mkdir. You don't have to learn shell commands.\n",
        "xp": 10,
        "success": {
          "type": "claude_tool_call",
          "match": {
            "tool": "Bash",
            "command_regex": "mkdir.*mi-trabajo"
          }
        },
        "success_title": "Nice! You have your folder",
        "success_sub": "10 XP. Now split it into four like you split your head."
      },
      {
        "id": "subcarpetas",
        "title": "Create the four subfolders",
        "body": "People, projects, companies, archive. It's the split that works for almost everyone. If you want to move things later, you'll do it as you go. Don't overthink it today.\n",
        "prompt": "now create four subfolders inside: 01-personas, 02-proyectos,\n03-empresas and 04-archivo\n",
        "hint": "Trick: numeric prefix on names. They always show up in the same order and your brain gets used to it.\n",
        "xp": 10,
        "success": {
          "type": "claude_tool_call",
          "match": {
            "tool": "Bash",
            "command_regex": "01-personas.*02-proyectos.*03-empresas.*04-archivo"
          }
        },
        "success_title": "Nice! Your structure is in place",
        "success_sub": "10 XP. Last step: give Claude your intro sheet."
      },
      {
        "id": "crear-claude-md",
        "title": "Give it a sheet that says who you are",
        "body": "A file called CLAUDE.md at the root of mi-trabajo. Claude reads it automatically every time you open a conversation from that folder. So you don't repeat yourself. Three paragraphs is plenty, don't write a biography.\n",
        "prompt": "create a CLAUDE.md at the root of mi-trabajo. Write that I\nwork at Empresa Prueba, that I prefer short answers in\nEnglish with no long bullet lists, and that my priorities\ntoday are closing the quarter and preparing the board\nmeeting.\n",
        "hint": "Trick: what you write today is ten lines. In a month it'll be thirty. It grows with use. You don't nail it on day one.\n",
        "xp": 10,
        "success": {
          "type": "file_contents_regex",
          "match": {
            "path": "/home/learner/empresa-prueba/mi-trabajo/CLAUDE.md",
            "regex": "(?is)(empresa prueba|priorities|short answers)"
          }
        },
        "success_title": "Nice! Claude knows who you are",
        "success_sub": "10 XP. Type /memory inside Claude to see this anytime."
      },
      {
        "id": "probar-la-memoria",
        "title": "Check Claude actually loaded it",
        "body": "To verify CLAUDE.md is in use, ask for something only that file can know. If it answers your priorities without you saying them, you're set.\n",
        "prompt": "without opening anything, tell me my priorities for today\n",
        "hint": "Trick: the /memory command inside Claude shows you every CLAUDE.md it's currently loading and where from. Useful when something doesn't add up.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)priorities"
        },
        "success_title": "Nice! Your head is now outside your head",
        "success_sub": "10 XP. Module 3 closed."
      }
    ],
    "on_complete": {
      "total_xp": 40,
      "takeaways": [
        "One root folder for your work, four clear subfolders.",
        "CLAUDE.md at the root, Claude reads it automatically.",
        "/memory shows you what's loaded right now.",
        "The file grows with use. You don't nail it on day one."
      ],
      "next_module": "m4-dia-a-dia",
      "trigger_signup": false
    }
  },
  {
    "id": "m3-organizar-cabeza",
    "module_number": 3,
    "language": "es",
    "title": "Organizar tu cabeza",
    "subtitle": "Una carpeta para tu trabajo y un archivo CLAUDE.md que dice quien eres",
    "description": "Crea la carpeta mi-trabajo dentro de Empresa Prueba con cuatro subcarpetas (personas, proyectos, empresas, archivo) y un archivo CLAUDE.md en la raiz que Claude Code leera automaticamente cada vez que abras una conversacion en esa carpeta.\n",
    "estimated_minutes": 8,
    "sandbox": "empresa-prueba",
    "mental_model": "Claude es el nuevo jefe de gabinete. Antes de pedirle nada, le dejas encima de la mesa una carpeta con tus cosas y una hoja que dice \"esto soy yo\". A partir de ahi trabaja solo.\n",
    "preconditions": {
      "working_directory": "/home/learner/empresa-prueba",
      "claude_running": true
    },
    "steps": [
      {
        "id": "crear-carpeta-raiz",
        "title": "Crea la carpeta de tu trabajo",
        "body": "Todo lo que metas aqui, Claude lo ve. Todo lo que no, no existe para el. Empezamos con una carpeta llamada mi-trabajo en la raiz de Empresa Prueba.\n",
        "prompt": "crea una carpeta llamada mi-trabajo en la raiz\n",
        "hint": "Truco: con que se lo pidas en lenguaje normal basta. Claude sabe traducirlo a un mkdir. No tienes que aprenderte comandos.\n",
        "xp": 10,
        "success": {
          "type": "claude_tool_call",
          "match": {
            "tool": "Bash",
            "command_regex": "mkdir.*mi-trabajo"
          }
        },
        "success_title": "¡Bien! Ya tienes tu carpeta",
        "success_sub": "Ganas 10 XP. Ahora dividela en cuatro como divides tu cabeza."
      },
      {
        "id": "subcarpetas",
        "title": "Crea las cuatro subcarpetas",
        "body": "Personas, proyectos, empresas, archivo. Es la division que le funciona a casi todo el mundo. Si despues quieres mover cosas, lo haras con el uso. No le des mas vueltas hoy.\n",
        "prompt": "ahora crea dentro cuatro subcarpetas: 01-personas,\n02-proyectos, 03-empresas y 04-archivo\n",
        "hint": "Truco: nombres con prefijo numerico. Asi siempre salen en el mismo orden y el cerebro se acostumbra.\n",
        "xp": 10,
        "success": {
          "type": "claude_tool_call",
          "match": {
            "tool": "Bash",
            "command_regex": "01-personas.*02-proyectos.*03-empresas.*04-archivo"
          }
        },
        "success_title": "¡Bien! Tu estructura ya esta montada",
        "success_sub": "Ganas 10 XP. Ultimo paso: dale a Claude tu hoja de presentacion."
      },
      {
        "id": "crear-claude-md",
        "title": "Dale una hoja que diga quien eres",
        "body": "Un archivo llamado CLAUDE.md en la raiz de mi-trabajo. Claude lo lee automaticamente cada vez que abres una conversacion desde esa carpeta. Asi no tienes que repetirte. Tres parrafos bastan, no escribas una biografia.\n",
        "prompt": "crea un CLAUDE.md en la raiz de mi-trabajo. Escribe que\ntrabajo en Empresa Prueba, que prefiero respuestas cortas\nen espanol y sin listas largas, y que mis prioridades hoy\nson cerrar el trimestre y preparar la junta.\n",
        "hint": "Truco: lo que escribas hoy son diez lineas. En un mes seran treinta. Crece con el uso. No clavas el dia uno.\n",
        "xp": 10,
        "success": {
          "type": "file_contents_regex",
          "match": {
            "path": "/home/learner/empresa-prueba/mi-trabajo/CLAUDE.md",
            "regex": "(?is)(empresa\\s+prueba|prioridades|respuestas\\s+cortas)"
          }
        },
        "success_title": "¡Bien! Claude ya sabe quien eres",
        "success_sub": "Ganas 10 XP. Manda /memory dentro de Claude para verlo cuando quieras."
      },
      {
        "id": "probar-la-memoria",
        "title": "Comprueba que Claude lo ha leido",
        "body": "Para verificar que CLAUDE.md esta en uso, le pides algo que solo puede saber por ese archivo. Si te responde con tus prioridades sin que se las digas, todo va.\n",
        "prompt": "sin abrir nada, dime cuales son mis prioridades de hoy\n",
        "hint": "Truco: el comando /memory dentro de Claude te muestra todos los CLAUDE.md que esta cargando ahora mismo, y desde donde. Util cuando algo no encaja.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)prioridades"
        },
        "success_title": "¡Bien! Tu cerebro ya esta fuera",
        "success_sub": "Ganas 10 XP. Modulo 3 cerrado."
      }
    ],
    "on_complete": {
      "total_xp": 40,
      "takeaways": [
        "Una carpeta raiz para tu trabajo y cuatro subcarpetas claras.",
        "CLAUDE.md en la raiz, Claude lo lee automaticamente.",
        "/memory te ensena que esta cargando ahora mismo.",
        "Crece el archivo con el uso, no lo clavas el dia uno."
      ],
      "next_module": "m4-dia-a-dia",
      "trigger_signup": false
    }
  },
  {
    "id": "m4-dia-a-dia",
    "module_number": 4,
    "language": "en",
    "title": "Day to day",
    "subtitle": "Morning brief, pre-meeting brief, capture, close-out",
    "description": "Four habits that change how you start and end the day. We start with the first question of the morning and finish with the last one of the afternoon. The whole conversation runs against ~/empresa-prueba with the CLAUDE.md you left in module 3.\n",
    "estimated_minutes": 9,
    "sandbox": "empresa-prueba",
    "mental_model": "It's not just another app. It's your desk. Coffee, Claude, first question of the day. Everything else flows through here.\n",
    "preconditions": {
      "working_directory": "/home/learner/empresa-prueba",
      "claude_running": true,
      "files_present": [
        "00-bandeja/calendario.md",
        "00-bandeja/inbox/"
      ]
    },
    "steps": [
      {
        "id": "parte-matinal",
        "title": "Ask for the morning brief",
        "body": "First question of the morning, always the same. Meetings, urgent emails, what you left open yesterday. Three blocks in under a minute.\n",
        "prompt": "Give me today's brief. Meetings, urgent emails, and what we\nleft open yesterday. Keep it short, three blocks.\n",
        "hint": "Trick: if you always ask in the same shape, tomorrow you turn it into a skill (module 6) and the copy-paste disappears.\n",
        "xp": 10,
        "success": {
          "type": "claude_tool_call",
          "match": {
            "tool": "Read",
            "path_regex": "(00-bandeja|calendario|inbox)"
          }
        },
        "success_title": "Nice! You have the day on one screen",
        "success_sub": "10 XP. Now do the brief before your first meeting."
      },
      {
        "id": "brief-pre-reunion",
        "title": "Pre-meeting brief",
        "body": "Two minutes before any meeting, instant brief. Who they are, last contact, open commitments, three things to cover. Your sandbox has Marta as the example, in 01-personas/marta.md.\n",
        "prompt": "I have a meeting in ten minutes with Marta. Tell me what we\nlast spoke about, open commitments, and three things I\nshould cover today.\n",
        "hint": "Trick: don't ask \"prep the meeting\". Ask for the concrete pieces. The answer comes back actionable, not a speech.\n",
        "xp": 10,
        "success": {
          "type": "claude_tool_call",
          "match": {
            "tool": "Read",
            "path_regex": "01-personas/marta"
          }
        },
        "success_title": "Nice! You walk in prepped",
        "success_sub": "10 XP. What matters is what happens after, let's go."
      },
      {
        "id": "registro-post-reunion",
        "title": "Capture without writing",
        "body": "Two minutes after the meeting, you tell Claude what happened in one sentence and it files in the right place. You don't write notes, you talk and it saves.\n",
        "prompt": "Just spoke with Marta. I asked her for the proposal by\nFriday, she asked me for the revised contract. File it on\nher sheet and remind me tomorrow.\n",
        "hint": "Trick: say it in order of who owes what. \"I asked for X, she asked for Y.\" That way you never forget what you have to deliver.\n",
        "xp": 10,
        "success": {
          "type": "claude_tool_call",
          "match": {
            "tool": "Edit",
            "path_regex": "01-personas/marta"
          }
        },
        "success_title": "Nice! The meeting is captured",
        "success_sub": "10 XP. One left: close the day."
      },
      {
        "id": "cierre-del-dia",
        "title": "Close the day",
        "body": "Last question before you shut down. What did you close, what did you move, what's open, plus a brief ready to open first thing tomorrow.\n",
        "prompt": "Summarize the day. What I closed, what I moved, what's\npending. And prep tomorrow's brief for first thing.\n",
        "hint": "Trick: this summary is the input for tomorrow's morning brief. Each day starts knowing where you left off, without you having to remember.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)(summarize|close|brief).{0,40}(day|tomorrow)"
        },
        "success_title": "Nice! The day is closed",
        "success_sub": "10 XP. Three weeks of this and it's a habit."
      }
    ],
    "on_complete": {
      "total_xp": 40,
      "takeaways": [
        "Start the day with the brief. Same question every morning.",
        "Two-minute brief before every meeting.",
        "Capture immediately after, by talking, not writing.",
        "Close with what's left and tomorrow's brief already done."
      ],
      "next_module": "m5-subagentes",
      "milestone_screen": "hito-dia7",
      "trigger_signup": false
    }
  },
  {
    "id": "m4-dia-a-dia",
    "module_number": 4,
    "language": "es",
    "title": "El dia a dia",
    "subtitle": "Parte matinal, briefs, registro, cierre",
    "description": "Cuatro habitos que cambian la forma de empezar y cerrar el dia. Empezamos por la primera pregunta de la manana y terminamos por la ultima de la tarde. La conversacion entera trabaja contra ~/empresa-prueba con el CLAUDE.md que dejaste en el modulo 3.\n",
    "estimated_minutes": 9,
    "sandbox": "empresa-prueba",
    "mental_model": "No es una app mas. Es tu mesa de trabajo. Cafe, Claude, primera pregunta del dia. Todo lo demas pasa por aqui.\n",
    "preconditions": {
      "working_directory": "/home/learner/empresa-prueba",
      "claude_running": true,
      "files_present": [
        "00-bandeja/calendario.md",
        "00-bandeja/inbox/"
      ]
    },
    "steps": [
      {
        "id": "parte-matinal",
        "title": "Pidele el parte del dia",
        "body": "Primera pregunta de la manana, siempre la misma. Reuniones, emails urgentes, lo que dejaste pendiente ayer. Tres bloques en menos de un minuto.\n",
        "prompt": "Dame el parte del dia. Reuniones, emails urgentes y lo que\ndejamos pendiente ayer. Que sea breve, tres bloques.\n",
        "hint": "Truco: si lo pides siempre con la misma estructura, manana lo conviertes en una skill (modulo 6) y desaparece el copy paste.\n",
        "xp": 10,
        "success": {
          "type": "claude_tool_call",
          "match": {
            "tool": "Read",
            "path_regex": "(00-bandeja|calendario|inbox)"
          }
        },
        "success_title": "¡Bien! Tienes el dia en una pantalla",
        "success_sub": "Ganas 10 XP. Sigue con el brief antes de tu primera reunion."
      },
      {
        "id": "brief-pre-reunion",
        "title": "Brief antes de una reunion",
        "body": "Dos minutos antes de cualquier reunion, brief instantaneo. Quien es, ultimo contacto, compromisos abiertos, tres temas a tocar. En tu sandbox tienes a Marta como ejemplo, en 01-personas/marta.md.\n",
        "prompt": "Me reuno en diez minutos con Marta. Dame lo ultimo que\nhemos hablado, compromisos abiertos y tres cosas que\ndeberia tocar hoy.\n",
        "hint": "Truco: no le pidas \"preparame la reunion\". Pidele las piezas concretas. Asi la respuesta es accionable, no un discurso.\n",
        "xp": 10,
        "success": {
          "type": "claude_tool_call",
          "match": {
            "tool": "Read",
            "path_regex": "01-personas/marta"
          }
        },
        "success_title": "¡Bien! Llegas a la reunion preparado",
        "success_sub": "Ganas 10 XP. Lo importante es lo que pasa despues, vamos."
      },
      {
        "id": "registro-post-reunion",
        "title": "Registra sin escribir",
        "body": "Dos minutos despues de la reunion, le cuentas a Claude que paso en una frase y el archiva en el sitio correcto. Tu no escribes notas, tu hablas y se guardan.\n",
        "prompt": "Acabo de hablar con Marta. Le pedi la propuesta para el\nviernes, ella me pidio el contrato revisado. Archivalo en\nsu ficha y recuerdamelo manana.\n",
        "hint": "Truco: dilo en orden de quien debe que. \"Le pedi X, me pidio Y.\" Asi nunca se te olvida lo que tienes que entregar.\n",
        "xp": 10,
        "success": {
          "type": "claude_tool_call",
          "match": {
            "tool": "Edit",
            "path_regex": "01-personas/marta"
          }
        },
        "success_title": "¡Bien! La reunion ya esta registrada",
        "success_sub": "Ganas 10 XP. Falta el cierre del dia."
      },
      {
        "id": "cierre-del-dia",
        "title": "Cierra el dia",
        "body": "Ultima pregunta antes de apagar. Que has cerrado, que has movido, que esta pendiente, y un brief listo para abrir manana a primera hora.\n",
        "prompt": "Resume el dia. Que he cerrado, que he movido, que queda\npendiente. Y prepara el brief de manana a primera hora.\n",
        "hint": "Truco: este resumen es el insumo del parte de la siguiente manana. Asi cada dia arranca sabiendo donde te quedaste, sin tener que recordar tu.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)(resume|cierra|brief).{0,40}(dia|manana)"
        },
        "success_title": "¡Bien! El dia esta cerrado",
        "success_sub": "Ganas 10 XP. Tres semanas haciendo esto y es rutina."
      }
    ],
    "on_complete": {
      "total_xp": 40,
      "takeaways": [
        "Arranca el dia con el parte. Misma pregunta cada manana.",
        "Brief de dos minutos antes de cada reunion.",
        "Registro inmediato al salir, hablando, no escribiendo.",
        "Cierre con lo que queda y el brief de manana ya preparado."
      ],
      "next_module": "m5-subagentes",
      "milestone_screen": "hito-dia7",
      "trigger_signup": false
    }
  },
  {
    "id": "m5-subagentes",
    "module_number": 5,
    "language": "en",
    "title": "Subagents",
    "subtitle": "Your invisible team of specialists",
    "description": "Claude Code doesn't have to do everything itself. You can define specialists (chief of staff, head of comms, analyst) each with their mission, model and tools. Claude auto-delegates based on the request.\n",
    "estimated_minutes": 9,
    "sandbox": "empresa-prueba",
    "mental_model": "Claude is your chief of staff. Subagents are the specialists it hires for you. You talk to the chief, the chief routes.\n",
    "preconditions": {
      "working_directory": "/home/learner/empresa-prueba/mi-trabajo",
      "claude_running": true
    },
    "steps": [
      {
        "id": "ver-subagentes-vacios",
        "title": "See what subagents you have today",
        "body": "Before creating any, check the state. The /agents command opens the list of subagents active in this project and in your user. Today it's empty.\n",
        "prompt": "/agents\n",
        "hint": "Trick: /agents also lets you create, edit and delete from a menu, but today we make it by hand so you see how it works under the hood.\n",
        "xp": 10,
        "success": {
          "type": "claude_slash_command",
          "match": {
            "command": "agents"
          }
        },
        "success_title": "Nice! You've seen the shelf is empty",
        "success_sub": "10 XP. Let's hire the first one."
      },
      {
        "id": "crear-jefe-de-agenda",
        "title": "Create the chief-of-agenda",
        "body": "Each subagent lives in .claude/agents/<name>/<name>.md with a frontmatter that says who it is, what it does and which model it uses. Claude reads the description to decide when to delegate.\n",
        "prompt": "create a subagent called jefe-de-agenda in .claude/agents.\nMission: manage my calendar, fit meetings without breaking\nprior commitments and flag open slots. Use claude-haiku-4-5\n(fast and cheap for agenda tasks) and give it read access\nto the calendar and edit access to the files in 01-personas.\n",
        "hint": "Trick: the frontmatter description is what matters most. The better it describes WHEN to use this subagent, the better Claude will activate it on its own.\n",
        "xp": 10,
        "success": {
          "type": "file_exists",
          "match": {
            "path": "/home/learner/empresa-prueba/mi-trabajo/.claude/agents/jefe-de-agenda/jefe-de-agenda.md"
          }
        },
        "success_title": "Nice! You have your first hire",
        "success_sub": "10 XP. Now check it and try it."
      },
      {
        "id": "invocar-jefe-de-agenda",
        "title": "Ask for something in its area without naming it",
        "body": "Real trick of subagents: you don't say \"use the jefe-de-agenda\". You ask for something in its area in plain language and Claude detects the match against the description. Good description, auto delegation.\n",
        "prompt": "fit a team dinner this week without breaking the Thursday\nmeeting\n",
        "hint": "Trick: if Claude doesn't auto-delegate, it's usually because the subagent's description is vague. Go back to the .md, sharpen WHEN it should be called, retry.\n",
        "xp": 10,
        "success": {
          "type": "claude_tool_call",
          "match": {
            "tool": "Task",
            "subagent_type": "jefe-de-agenda"
          }
        },
        "success_title": "Nice! Claude delegated to the specialist",
        "success_sub": "10 XP. Last step: the rule of NOT making more."
      },
      {
        "id": "regla-de-no-multiplicar",
        "title": "The rule of not multiplying them",
        "body": "Two or three sharp subagents beat ten vague ones. Start with the one that hurts most. Add when you feel the gap again. Before closing the module, read the .md you just made and improve it.\n",
        "prompt": "reread the jefe-de-agenda .md and propose three\nimprovements to make its description sharper. Don't edit,\njust propose.\n",
        "hint": "Trick: reviewing the .md is the user's work, not Claude's. Ask for proposals, decide yourself, edit yourself. That way you keep control over who does what in your invisible team.\n",
        "xp": 10,
        "success": {
          "type": "claude_tool_call",
          "match": {
            "tool": "Read",
            "path_regex": ".claude/agents/jefe-de-agenda"
          }
        },
        "success_title": "Nice! You know how to grow the team",
        "success_sub": "10 XP. Module 5 closed."
      }
    ],
    "on_complete": {
      "total_xp": 40,
      "takeaways": [
        "Subagents live in .claude/agents/<name>/<name>.md",
        "The description field rules. Claude reads it to auto-delegate.",
        "You don't invoke them by hand, the request triggers them.",
        "Start with one, grow by need. Don't multiply."
      ],
      "next_module": "m6-skills",
      "trigger_signup": false
    }
  },
  {
    "id": "m5-subagentes",
    "module_number": 5,
    "language": "es",
    "title": "Subagentes",
    "subtitle": "Tu equipo invisible de especialistas",
    "description": "Claude Code no tiene que hacerlo todo el. Puedes definir especialistas (jefe de agenda, jefe de comunicacion, analista) cada uno con su mision, su modelo y sus herramientas. Claude auto-delega segun la peticion.\n",
    "estimated_minutes": 9,
    "sandbox": "empresa-prueba",
    "mental_model": "Claude es tu jefe de gabinete. Los subagentes son los especialistas que el contrata por ti. Tu hablas con el jefe, el reparte.\n",
    "preconditions": {
      "working_directory": "/home/learner/empresa-prueba/mi-trabajo",
      "claude_running": true
    },
    "steps": [
      {
        "id": "ver-subagentes-vacios",
        "title": "Mira que subagentes tienes hoy",
        "body": "Antes de crear ninguno, comprueba el estado. El comando /agents te abre la lista de subagentes activos en este proyecto y en tu usuario. Hoy esta vacio.\n",
        "prompt": "/agents\n",
        "hint": "Truco: /agents tambien sirve para crear, editar y borrar desde un menu, pero hoy lo creamos a mano para que veas como funciona por dentro.\n",
        "xp": 10,
        "success": {
          "type": "claude_slash_command",
          "match": {
            "command": "agents"
          }
        },
        "success_title": "¡Bien! Has visto que la estanteria esta vacia",
        "success_sub": "Ganas 10 XP. Vamos a fichar al primero."
      },
      {
        "id": "crear-jefe-de-agenda",
        "title": "Crea el jefe de agenda",
        "body": "Cada subagente vive en .claude/agents/<nombre>/<nombre>.md con un frontmatter que dice quien es, que hace y que modelo usa. Claude lee la description para decidir cuando delegarle.\n",
        "prompt": "crea un subagente llamado jefe-de-agenda en .claude/agents.\nSu mision: gestionar mi calendario, encajar reuniones sin\nromper compromisos previos y avisarme de huecos. Usa\nclaude-haiku-4-5 (es rapido y barato para tareas de agenda)\ny dale permisos de lectura del calendario y edicion de los\narchivos en 01-personas.\n",
        "hint": "Truco: la description del frontmatter es la que mas pesa. Cuanto mejor describa CUANDO usar este subagente, mejor lo activara Claude por su cuenta.\n",
        "xp": 10,
        "success": {
          "type": "file_exists",
          "match": {
            "path": "/home/learner/empresa-prueba/mi-trabajo/.claude/agents/jefe-de-agenda/jefe-de-agenda.md"
          }
        },
        "success_title": "¡Bien! Tienes tu primer fichaje",
        "success_sub": "Ganas 10 XP. Ahora compruebalo y pruebalo."
      },
      {
        "id": "invocar-jefe-de-agenda",
        "title": "Pidele algo de su area sin nombrarlo",
        "body": "Truco real de subagentes: tu no dices \"usa el jefe de agenda\". Le pides algo de su area en lenguaje normal y Claude detecta el match con la description. Si la description es buena, delega solo.\n",
        "prompt": "encajame una cena con el equipo esta semana sin pisar la\nreunion del jueves\n",
        "hint": "Truco: si Claude no auto-delega, suele ser porque la description del subagente es vaga. Vuelve al .md, especifica mejor cuando se le debe llamar y reintenta.\n",
        "xp": 10,
        "success": {
          "type": "claude_tool_call",
          "match": {
            "tool": "Task",
            "subagent_type": "jefe-de-agenda"
          }
        },
        "success_title": "¡Bien! Claude ha delegado al especialista",
        "success_sub": "Ganas 10 XP. Ultimo paso: la regla de cuando NO crear mas."
      },
      {
        "id": "regla-de-no-multiplicar",
        "title": "La regla de no multiplicarlos",
        "body": "Dos o tres subagentes bien afinados valen mas que diez vagos. Empieza con el que mas duele no tener. Anade cuando vuelvas a notar la falta. Antes de cerrar el modulo, lee el .md que has creado y mejoralo.\n",
        "prompt": "relee el .md del jefe-de-agenda y proponme tres mejoras\npara que su description sea mas precisa. No edites,\nproponlas.\n",
        "hint": "Truco: revisar el .md es trabajo del usuario, no de Claude. Pidele propuestas, decide tu, edita tu. Asi mantienes control sobre quien hace que en tu equipo invisible.\n",
        "xp": 10,
        "success": {
          "type": "claude_tool_call",
          "match": {
            "tool": "Read",
            "path_regex": ".claude/agents/jefe-de-agenda"
          }
        },
        "success_title": "¡Bien! Ya sabes hacer crecer el equipo",
        "success_sub": "Ganas 10 XP. Modulo 5 cerrado."
      }
    ],
    "on_complete": {
      "total_xp": 40,
      "takeaways": [
        "Subagentes viven en .claude/agents/<nombre>/<nombre>.md",
        "El campo description manda, Claude lo lee para auto-delegar.",
        "Tu no los invocas a mano, los activa la peticion.",
        "Empieza con uno, crece por necesidad. No multipliques."
      ],
      "next_module": "m6-skills",
      "trigger_signup": false
    }
  },
  {
    "id": "m6-skills",
    "module_number": 6,
    "language": "en",
    "title": "Skills",
    "subtitle": "Your favorite shortcuts, saved",
    "description": "If you repeat the same instruction every morning, that's not a conversation, that's a procedure. A skill is that procedure saved, with a short name, that Claude runs when invoked.\n",
    "estimated_minutes": 8,
    "sandbox": "empresa-prueba",
    "mental_model": "Subagent is WHO. Skill is HOW. The head of comms can have a skill \"linkedin-post\" and a skill \"press-release\". Same brain, different recipes.\n",
    "preconditions": {
      "working_directory": "/home/learner/empresa-prueba/mi-trabajo",
      "claude_running": true
    },
    "steps": [
      {
        "id": "regla-tres-veces",
        "title": "The rule of three",
        "body": "If you've asked for the same thing three times, it's a candidate for a skill. If only once, not yet. In module 4 you already asked for the morning brief. If you'll ask every day, that's our first candidate.\n",
        "prompt": "look at my last conversation with you and tell me which\nthree patterns repeat that would be worth saving as a\nskill\n",
        "hint": "Trick: let Claude detect the patterns. Your bias is to think you repeat less than you actually do.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)(patterns|repeat|skill)"
        },
        "success_title": "Nice! You have candidates",
        "success_sub": "10 XP. Let's save the first one."
      },
      {
        "id": "crear-skill-parte-matinal",
        "title": "Create the parte-matinal skill",
        "body": "Each skill lives in .claude/skills/<name>/SKILL.md with a frontmatter that says when to use it and optionally what tools are pre-approved. The markdown body is the step-by-step instructions Claude follows.\n",
        "prompt": "create a skill called parte-matinal in .claude/skills.\nDescription: use every morning when opening Claude to get\nthe day's brief. Steps: read 00-bandeja/calendario.md,\nread 00-bandeja/inbox/, look at 01-personas for open\nitems and return a four-bullet brief always in the same\nformat (meetings, urgent, yesterday's open, today's focus).\n",
        "hint": "Trick: the more concrete the steps, the more consistent the response every morning. A vague skill is just another conversation, not a recipe.\n",
        "xp": 10,
        "success": {
          "type": "file_exists",
          "match": {
            "path": "/home/learner/empresa-prueba/mi-trabajo/.claude/skills/parte-matinal/SKILL.md"
          }
        },
        "success_title": "Nice! Your first skill is saved",
        "success_sub": "10 XP. Try it with /parte-matinal."
      },
      {
        "id": "invocar-skill",
        "title": "Invoke it",
        "body": "Once saved, you launch it with /<name>. Claude loads the recipe just at that moment (unlike CLAUDE.md which loads always) and executes. Seconds instead of minutes.\n",
        "prompt": "/parte-matinal\n",
        "hint": "Trick: you could also say \"give me the brief\" in plain language and Claude would activate it via the description. But typing /parte-matinal is fastest and always works.\n",
        "xp": 10,
        "success": {
          "type": "claude_slash_command",
          "match": {
            "command": "parte-matinal"
          }
        },
        "success_title": "Nice! You ran your first recipe",
        "success_sub": "10 XP. One important idea left."
      },
      {
        "id": "skill-vs-subagente",
        "title": "Review the difference vs. a subagent",
        "body": "Skill: recipe. Same Claude, saved instructions. Loads only when invoked. Subagent: specialist. Different context, different mission, different model. Ask Claude to clarify in its own words.\n",
        "prompt": "explain in four sentences the difference between a skill\nand a subagent, with a concrete example using the\njefe-de-agenda I made yesterday.\n",
        "hint": "Trick: if one day you doubt whether to make a skill or a subagent, ask \"do I need another head or just another recipe?\". Another head is subagent. Another recipe is skill.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)(skill).{0,40}(subagent)"
        },
        "success_title": "Nice! You can tell them apart",
        "success_sub": "10 XP. Module 6 closed."
      }
    ],
    "on_complete": {
      "total_xp": 40,
      "takeaways": [
        "Skill = recipe saved at .claude/skills/<name>/SKILL.md",
        "Loads only when invoked, not always like CLAUDE.md",
        "Invoke with /<name> or via description in plain language",
        "Rule of three before creating one."
      ],
      "next_module": "m7-mcps",
      "trigger_signup": false
    }
  },
  {
    "id": "m6-skills",
    "module_number": 6,
    "language": "es",
    "title": "Skills",
    "subtitle": "Tus atajos favoritos, guardados",
    "description": "Si cada manana repites la misma instruccion, eso no es una conversacion, es un procedimiento. Una skill es ese procedimiento guardado, con un nombre corto, que Claude ejecuta cuando lo invocas.\n",
    "estimated_minutes": 8,
    "sandbox": "empresa-prueba",
    "mental_model": "Subagente es QUIEN. Skill es COMO. El jefe de comunicacion puede tener la skill \"post-linkedin\" y la skill \"nota-prensa\". Mismo cerebro, recetas distintas.\n",
    "preconditions": {
      "working_directory": "/home/learner/empresa-prueba/mi-trabajo",
      "claude_running": true
    },
    "steps": [
      {
        "id": "regla-tres-veces",
        "title": "La regla de las tres veces",
        "body": "Si has pedido lo mismo tres veces, es candidato a skill. Si solo lo has pedido una vez, todavia no. En el modulo 4 ya pediste el parte matinal. Si lo vas a pedir cada dia, es nuestra primera candidata.\n",
        "prompt": "mira mi ultima conversacion contigo y dime que tres\npatrones se repiten que valdria la pena guardar como\nskill\n",
        "hint": "Truco: deja que Claude detecte los patrones. Tu sesgo es pensar que repites menos de lo que repites.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)(patrones|repiten|skill)"
        },
        "success_title": "¡Bien! Tienes candidatas",
        "success_sub": "Ganas 10 XP. Vamos a guardar la primera."
      },
      {
        "id": "crear-skill-parte-matinal",
        "title": "Crea la skill parte-matinal",
        "body": "Cada skill vive en .claude/skills/<nombre>/SKILL.md con un frontmatter que dice cuando usarla y opcionalmente que herramientas tiene preaprobadas. El cuerpo en markdown son las instrucciones que Claude sigue paso a paso.\n",
        "prompt": "crea una skill llamada parte-matinal en .claude/skills.\nDescription: usar cada manana al abrir Claude para tener\nel resumen del dia. Pasos: leer 00-bandeja/calendario.md,\nleer 00-bandeja/inbox/, mirar 01-personas para pendientes\ny devolver un brief de cuatro bullets siempre con el mismo\nformato (reuniones, urgentes, pendientes ayer, foco hoy).\n",
        "hint": "Truco: cuanto mas concretos los pasos, mas consistente la respuesta cada manana. Una skill ambigua es una conversacion mas, no una receta.\n",
        "xp": 10,
        "success": {
          "type": "file_exists",
          "match": {
            "path": "/home/learner/empresa-prueba/mi-trabajo/.claude/skills/parte-matinal/SKILL.md"
          }
        },
        "success_title": "¡Bien! Tu primera skill esta guardada",
        "success_sub": "Ganas 10 XP. Pruebala con /parte-matinal."
      },
      {
        "id": "invocar-skill",
        "title": "Invocala",
        "body": "Una vez guardada, la lanzas con /<nombre>. Claude carga la receta solo en ese momento (a diferencia de CLAUDE.md que carga siempre) y la ejecuta. Segundos en vez de minutos.\n",
        "prompt": "/parte-matinal\n",
        "hint": "Truco: tambien podrias decir \"lanzame el parte\" en lenguaje normal y Claude la activaria por la description. Pero escribir /parte-matinal es lo mas rapido y siempre funciona.\n",
        "xp": 10,
        "success": {
          "type": "claude_slash_command",
          "match": {
            "command": "parte-matinal"
          }
        },
        "success_title": "¡Bien! Has ejecutado tu primera receta",
        "success_sub": "Ganas 10 XP. Falta una idea importante."
      },
      {
        "id": "skill-vs-subagente",
        "title": "Repasa la diferencia con un subagente",
        "body": "Skill: receta. Mismo Claude, instrucciones guardadas. Carga solo cuando la invocas. Subagente: especialista. Otro contexto, otra mision, otro modelo. Pidele a Claude que te lo aclare en su jerga.\n",
        "prompt": "explicame en cuatro frases la diferencia entre una skill y\nun subagente, con un ejemplo concreto del jefe-de-agenda\nque cree ayer.\n",
        "hint": "Truco: si un dia dudas si crear skill o subagente, pregunta \"necesito otra cabeza o solo otra receta?\". Otra cabeza es subagente. Otra receta es skill.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)(skill).{0,40}(subagente|subagent)"
        },
        "success_title": "¡Bien! Ya distingues una de la otra",
        "success_sub": "Ganas 10 XP. Modulo 6 cerrado."
      }
    ],
    "on_complete": {
      "total_xp": 40,
      "takeaways": [
        "Skill = receta guardada en .claude/skills/<nombre>/SKILL.md",
        "Se carga solo al invocarla, no permanente como CLAUDE.md",
        "Invocas con /<nombre> o por la description en lenguaje normal",
        "Regla de las tres veces antes de crear una."
      ],
      "next_module": "m7-mcps",
      "trigger_signup": false
    }
  },
  {
    "id": "m7-mcps",
    "module_number": 7,
    "language": "en",
    "title": "MCPs",
    "subtitle": "Connect Claude to your real tools",
    "description": "Until now Claude lived inside your folder. An MCP (Model Context Protocol) is a standard plug giving it access to tools: the filesystem, GitHub, Gmail, Drive, Slack. It goes from reading to doing.\n",
    "estimated_minutes": 9,
    "sandbox": "empresa-prueba",
    "mental_model": "Without MCP, Claude says \"you should send this email\". With MCP, it sends it. Without MCP, \"you have a slot Tuesday\". With MCP, it books the meeting. The name doesn't matter. Think of it as a universal plug.\n",
    "preconditions": {
      "working_directory": "/home/learner/empresa-prueba/mi-trabajo",
      "claude_running": true
    },
    "steps": [
      {
        "id": "ver-mcps-actuales",
        "title": "See what MCPs you have",
        "body": "Like with /agents and /skills, there's a command to see the state. /mcp lists the MCP servers active in this project and at the user level. Today it's empty.\n",
        "prompt": "/mcp\n",
        "hint": "Trick: /mcp also lets you manage authentication for already connected MCPs. Useful when something stops working.\n",
        "xp": 10,
        "success": {
          "type": "claude_slash_command",
          "match": {
            "command": "mcp"
          }
        },
        "success_title": "Nice! Inventory done",
        "success_sub": "10 XP. Let's plug in the first one."
      },
      {
        "id": "anadir-filesystem-mcp",
        "title": "Connect the filesystem MCP",
        "body": "It's the simplest to try and needs no credentials. With it, Claude can read and edit files outside ~/empresa-prueba if you allow them. You add it via command line with `claude mcp add`.\n",
        "prompt": "add a filesystem MCP using npx\n@anthropic-ai/build-mcp-server-filesystem and give it\naccess to the folder ~/empresa-prueba/mi-trabajo\n",
        "hint": "Trick: the first time an MCP attempts a sensitive action, Claude asks for confirmation on screen. It doesn't act behind your back. You're in charge.\n",
        "xp": 10,
        "success": {
          "type": "claude_tool_call",
          "match": {
            "tool": "Bash",
            "command_regex": "claude\\s+mcp\\s+add.*filesystem"
          }
        },
        "success_title": "Nice! First plug is in",
        "success_sub": "10 XP. Try it on the next step."
      },
      {
        "id": "usar-filesystem-mcp",
        "title": "Use it",
        "body": "Once plugged in, you don't have to do anything different in your prompts. Claude detects the MCP and uses it when appropriate. Ask it to list your subfolders going through the MCP.\n",
        "prompt": "using the filesystem MCP, list every file in mi-trabajo\nand tell me which ones I've modified in the last seven\ndays\n",
        "hint": "Trick: if you're not sure whether Claude is using the MCP or its internal tools, ask \"what tool did you use and why?\". It tells you.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)(filesystem|mcp).{0,60}(list|files)"
        },
        "success_title": "Nice! You ran your first action via MCP",
        "success_sub": "10 XP. Last step, important."
      },
      {
        "id": "limites-y-permiso",
        "title": "The MCP golden rule",
        "body": "The interesting MCPs (Gmail, Drive, banking) open the door to sensitive actions: send emails, transfer money, delete. Before any of those, Claude asks for confirmation. You're in charge, it executes only what you authorize. Always.\n",
        "prompt": "explain in three sentences what would happen if I connected a Gmail MCP and asked you \"reply to Pedro and book the meeting\". What would you do and what would you ask me first?\n",
        "hint": "Trick: if an MCP attempts a sensitive action without asking for confirmation, that MCP is misconfigured. Remove it and flag it.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)(gmail|confirmation|permission|ask)"
        },
        "success_title": "Nice! You closed the module knowing the limit",
        "success_sub": "10 XP. Module 7 closed."
      }
    ],
    "on_complete": {
      "total_xp": 40,
      "takeaways": [
        "MCP = standard plug between Claude and other tools.",
        "Add with `claude mcp add <name> <config>`.",
        "Filesystem is the safe first step, no credentials.",
        "Sensitive actions ALWAYS ask for confirmation. You decide."
      ],
      "next_module": "m8-vida-ai-native",
      "trigger_signup": false
    }
  },
  {
    "id": "m7-mcps",
    "module_number": 7,
    "language": "es",
    "title": "MCPs",
    "subtitle": "Conectar Claude con tus herramientas reales",
    "description": "Hasta ahora Claude vivia dentro de tu carpeta. Un MCP (Model Context Protocol) es un enchufe estandar para darle acceso a herramientas: el sistema de archivos, GitHub, Gmail, Drive, Slack. Pasa de leer a hacer.\n",
    "estimated_minutes": 9,
    "sandbox": "empresa-prueba",
    "mental_model": "Sin MCP, Claude te dice \"deberias mandar este email\". Con MCP, lo manda. Sin MCP, \"tienes hueco el martes\". Con MCP, agenda la reunion. El nombre no importa. Piensa en un enchufe universal.\n",
    "preconditions": {
      "working_directory": "/home/learner/empresa-prueba/mi-trabajo",
      "claude_running": true
    },
    "steps": [
      {
        "id": "ver-mcps-actuales",
        "title": "Mira que MCPs tienes ya",
        "body": "Como con /agents y /skills, hay un comando para ver el estado. /mcp te lista los servidores MCP activos en este proyecto y a nivel usuario. Hoy esta vacio.\n",
        "prompt": "/mcp\n",
        "hint": "Truco: /mcp tambien te permite gestionar autenticaciones de MCPs ya conectados. Util cuando algo deja de funcionar.\n",
        "xp": 10,
        "success": {
          "type": "claude_slash_command",
          "match": {
            "command": "mcp"
          }
        },
        "success_title": "¡Bien! Inventario hecho",
        "success_sub": "Ganas 10 XP. Vamos a enchufar el primero."
      },
      {
        "id": "anadir-filesystem-mcp",
        "title": "Conecta el MCP de filesystem",
        "body": "Es el mas simple de probar y no necesita credenciales. Con el, Claude puede leer y editar archivos fuera de ~/empresa-prueba si los autorizas. Lo anades por linea de comandos con claude mcp add.\n",
        "prompt": "anademe un MCP de filesystem usando npx\n@anthropic-ai/build-mcp-server-filesystem y dale acceso a\nla carpeta ~/empresa-prueba/mi-trabajo\n",
        "hint": "Truco: la primera vez que un MCP intenta una accion sensible, Claude te pide confirmacion en pantalla. No actua a tus espaldas. Tu mandas.\n",
        "xp": 10,
        "success": {
          "type": "claude_tool_call",
          "match": {
            "tool": "Bash",
            "command_regex": "claude\\s+mcp\\s+add.*filesystem"
          }
        },
        "success_title": "¡Bien! El primer enchufe esta puesto",
        "success_sub": "Ganas 10 XP. Pruebalo en el siguiente paso."
      },
      {
        "id": "usar-filesystem-mcp",
        "title": "Usalo",
        "body": "Una vez enchufado, no tienes que hacer nada distinto en tus prompts. Claude detecta el MCP y lo usa cuando conviene. Pidele que liste tus subcarpetas pasando por el MCP.\n",
        "prompt": "usando el MCP de filesystem, listame todos los archivos\nde mi-trabajo y dime cuales he modificado en los ultimos\nsiete dias\n",
        "hint": "Truco: si dudas si Claude esta usando el MCP o sus tools internas, pregunta \"¿que herramienta has usado y por que?\". Te lo cuenta.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)(filesystem|mcp).{0,60}(listame|listar|archivos)"
        },
        "success_title": "¡Bien! Has hecho tu primera accion via MCP",
        "success_sub": "Ganas 10 XP. Ultimo paso, importante."
      },
      {
        "id": "limites-y-permiso",
        "title": "La regla de oro de los MCPs",
        "body": "Los MCPs interesantes (Gmail, Drive, banco) abren la puerta a acciones sensibles: enviar emails, transferir, borrar. Antes de cualquiera de esas, Claude te pide confirmacion. Tu mandas, el ejecuta solo lo autorizado. Siempre.\n",
        "prompt": "explicame en tres frases que pasaria si conectara un MCP de Gmail y te pidiera \"responde a Pedro y agenda la reunion\". ¿Que harias tu y que me preguntarias antes?\n",
        "hint": "Truco: si un MCP intenta una accion sin pedirte confirmacion, ese MCP esta mal configurado. Quitalo y avisanos.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)(gmail|confirmacion|permiso|preguntaria)"
        },
        "success_title": "¡Bien! Has cerrado el modulo entendiendo el limite",
        "success_sub": "Ganas 10 XP. Modulo 7 cerrado."
      }
    ],
    "on_complete": {
      "total_xp": 40,
      "takeaways": [
        "MCP = enchufe estandar entre Claude y otras herramientas.",
        "Se anade con `claude mcp add <nombre> <config>`.",
        "Filesystem es el primer paso seguro, sin credenciales.",
        "Acciones sensibles SIEMPRE piden confirmacion. Tu mandas."
      ],
      "next_module": "m8-vida-ai-native",
      "trigger_signup": false
    }
  },
  {
    "id": "m8-vida-ai-native",
    "module_number": 8,
    "language": "en",
    "title": "Your AI-native life",
    "subtitle": "When working with Claude stops being a novelty and becomes the norm",
    "description": "Course closer. We review the seven modules as habits, not as commands, and leave a personal manifesto in mi-trabajo with three rules the user takes back to real work.\n",
    "estimated_minutes": 7,
    "sandbox": "empresa-prueba",
    "mental_model": "AI-native isn't using AI. It's designing your work assuming it's there. Like nobody \"uses electricity\", everything just runs on it. You no longer use AI, you live alongside it.\n",
    "preconditions": {
      "working_directory": "/home/learner/empresa-prueba/mi-trabajo",
      "claude_running": true
    },
    "steps": [
      {
        "id": "balance-de-modulos",
        "title": "Ask Claude for your course balance",
        "body": "Before closing, look at the road traveled. Subagents, skills, CLAUDE.md, MCPs, daily routine. Ask Claude to map what you have active and what you barely use.\n",
        "prompt": "look at my mi-trabajo folder (CLAUDE.md, agents, skills,\nmcps) and give me a map of what I have active, what I use\nlittle, and what I haven't touched yet. Honest, no\nsugarcoating.\n",
        "hint": "Trick: this is a good prompt to repeat every month and see how your setup grows. More isn't better, sharp is.\n",
        "xp": 10,
        "success": {
          "type": "claude_tool_call",
          "match": {
            "tool": "Read",
            "path_regex": "mi-trabajo"
          }
        },
        "success_title": "Nice! You have the map of your setup",
        "success_sub": "10 XP. On to the key question."
      },
      {
        "id": "la-pregunta-diaria",
        "title": "The question you take with you",
        "body": "Every time you start a task, one question: \"do I have to do this myself?\". If no, Claude. If yes, Claude alongside. Ask Claude to frame it as a desktop reminder.\n",
        "prompt": "frame this sentence in few words as a desktop reminder:\n\"do I have to do this myself?\". Make it memorable, no\ncheese.\n",
        "hint": "Trick: this question is worth more than the hundred skills you might save. It's the shift from tool to environment.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)(do I have to|myself|reminder)"
        },
        "success_title": "Nice! You have the question",
        "success_sub": "10 XP. Let's write it down."
      },
      {
        "id": "manifiesto-personal",
        "title": "Write your manifesto in three rules",
        "body": "Close with a manifesto.md in mi-trabajo. Three rules of yours, not the platform's. What you'll do tomorrow when you open your laptop. What you'll stop doing. What decision Claude gets to make for you without asking and which one not.\n",
        "prompt": "create a manifesto.md in mi-trabajo with three rules of\nmine:\n1) what I'll do tomorrow when I open my laptop,\n2) what I'll stop doing,\n3) what decision I let you make alone and which one not.\nMake a first proposal based on what you've seen this week\nof the course, then I edit.\n",
        "hint": "Trick: the manifesto grows. Three lines today are ten in six months. But the first three have to be in place before this module closes.\n",
        "xp": 10,
        "success": {
          "type": "file_exists",
          "match": {
            "path": "/home/learner/empresa-prueba/mi-trabajo/manifesto.md"
          }
        },
        "success_title": "Nice! Manifesto saved",
        "success_sub": "10 XP. Last step."
      },
      {
        "id": "cierre-y-traslado",
        "title": "Take it back to real work",
        "body": "The sandbox was a fictional company. What you learned works the same in your real work: same folder, same CLAUDE.md, same skills, same subagents. The change is you don't practice anymore, you live it.\n",
        "prompt": "write me a three-paragraph email to my future self next\nMonday, reminding me what to open first, which skill to\nrun, and why the sandbox was just a rehearsal.\n",
        "hint": "Trick: this is the last prompt you send in the sandbox. Paste it on next Monday in your real calendar when you walk out of here.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)(email|monday|reminder)"
        },
        "success_title": "Nice! Course completed",
        "success_sub": "10 XP. You've mastered Claude Code. Welcome to the other side."
      }
    ],
    "on_complete": {
      "total_xp": 40,
      "takeaways": [
        "Week 1, friction. Month 1, routine. Quarter, leverage.",
        "The daily question: do I have to do this myself?",
        "The manifesto grows, you sharpen it with use.",
        "The sandbox was the rehearsal. Next Monday is opening night."
      ],
      "next_module": null,
      "course_complete": true,
      "trigger_signup": false
    }
  },
  {
    "id": "m8-vida-ai-native",
    "module_number": 8,
    "language": "es",
    "title": "Tu vida AI-native",
    "subtitle": "Cuando trabajar con Claude deja de ser novedad y pasa a ser norma",
    "description": "Cierre del curso. Repasamos los siete modulos en clave de habito, no de comando, y dejamos un manifiesto personal en mi-trabajo con tres reglas que el usuario se lleva a su trabajo real.\n",
    "estimated_minutes": 7,
    "sandbox": "empresa-prueba",
    "mental_model": "AI-native no es usar IA. Es disenar tu trabajo asumiendo que esta ahi. Igual que nadie \"usa electricidad\", simplemente todo funciona con ella. Tu ya no usas IA, vives con ella al lado.\n",
    "preconditions": {
      "working_directory": "/home/learner/empresa-prueba/mi-trabajo",
      "claude_running": true
    },
    "steps": [
      {
        "id": "balance-de-modulos",
        "title": "Pidele a Claude el balance de tu curso",
        "body": "Antes de cerrar, mira lo recorrido. Subagentes, skills, CLAUDE.md, MCPs, rutina diaria. Pidele a Claude que te haga un mapa de lo que tienes activo y lo que apenas usas.\n",
        "prompt": "mira mi carpeta mi-trabajo (CLAUDE.md, agents, skills, mcps)\ny dame un mapa de lo que tengo activo, lo que uso poco y\nlo que aun no he tocado. Honesto, sin adornar.\n",
        "hint": "Truco: este es un buen prompt para repetir cada mes y ver como crece tu setup. Mas no es mejor: bien afinado lo es.\n",
        "xp": 10,
        "success": {
          "type": "claude_tool_call",
          "match": {
            "tool": "Read",
            "path_regex": "mi-trabajo"
          }
        },
        "success_title": "¡Bien! Tienes el mapa de tu setup",
        "success_sub": "Ganas 10 XP. Vamos a la pregunta clave."
      },
      {
        "id": "la-pregunta-diaria",
        "title": "La pregunta que te vas a llevar",
        "body": "Cada vez que empiezas una tarea, una pregunta: \"¿esto lo tengo que hacer yo?\". Si la respuesta es no, Claude. Si es si, Claude al lado. Pidele que te la enmarque.\n",
        "prompt": "enmarca esta frase en pocas palabras como recordatorio\npara mi escritorio: \"esto lo tengo que hacer yo?\". Hazla\nmemorable, sin cursilerias.\n",
        "hint": "Truco: esta pregunta vale mas que las cien skills que podrias guardar. Es el cambio de chip de herramienta a entorno.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)(esto lo tengo|yo|recordatorio)"
        },
        "success_title": "¡Bien! Ya tienes la pregunta",
        "success_sub": "Ganas 10 XP. Vamos a dejarla escrita."
      },
      {
        "id": "manifiesto-personal",
        "title": "Escribe tu manifiesto en tres reglas",
        "body": "Cierra con un archivo manifiesto.md en mi-trabajo. Tres reglas tuyas, no de la plataforma. Que vas a hacer manana al abrir el portatil. Que vas a dejar de hacer. Que decision toma Claude por ti sin preguntar y cual no.\n",
        "prompt": "crea un manifiesto.md en mi-trabajo con tres reglas mias:\n1) que voy a hacer manana al abrir el portatil,\n2) que voy a dejar de hacer,\n3) que decision te dejo tomar sola y cual no.\nHazme una primera propuesta basada en lo que has visto en\nesta semana de curso, despues yo la edito.\n",
        "hint": "Truco: el manifiesto crece. Lo que escribes hoy en tres lineas en seis meses son diez. Pero las tres primeras tienen que estar antes de cerrar este modulo.\n",
        "xp": 10,
        "success": {
          "type": "file_exists",
          "match": {
            "path": "/home/learner/empresa-prueba/mi-trabajo/manifiesto.md"
          }
        },
        "success_title": "¡Bien! Manifiesto guardado",
        "success_sub": "Ganas 10 XP. Ultimo paso."
      },
      {
        "id": "cierre-y-traslado",
        "title": "Llevatelo a tu trabajo de verdad",
        "body": "El sandbox era una empresa ficticia. Lo aprendido sirve tal cual en tu trabajo real: misma carpeta, mismo CLAUDE.md, mismas skills, mismos subagentes. El cambio es que ya no practicas, vives.\n",
        "prompt": "escribeme un email de tres parrafos a mi yo del lunes\nsiguiente, recordandole que abrir lo primero, que skill\nlanzar y por que el sandbox era solo un ensayo.\n",
        "hint": "Truco: este es el ultimo prompt que envias en el sandbox. Pegalo al lunes en tu calendario real cuando salgas de aqui.\n",
        "xp": 10,
        "success": {
          "type": "claude_prompt_sent",
          "match_regex": "(?i)(email|lunes|monday|recordatorio)"
        },
        "success_title": "¡Bien! Curso completado",
        "success_sub": "Ganas 10 XP. Ya dominas Claude Code. Bienvenido al otro lado."
      }
    ],
    "on_complete": {
      "total_xp": 40,
      "takeaways": [
        "Semana 1, fricciones. Mes 1, rutina. Trimestre, apalancamiento.",
        "La pregunta diaria: ¿esto lo tengo que hacer yo?",
        "El manifiesto crece, lo afinas con el uso.",
        "El sandbox era el ensayo. El siguiente lunes es el estreno."
      ],
      "next_module": null,
      "course_complete": true,
      "trigger_signup": false
    }
  }
];
