#!/usr/bin/env node
// Reads ../lessons/*.yml at build time, emits lib/lessons-generated.ts so
// the Next.js build never depends on filesystem access at runtime. Runs
// as `predev` and `prebuild` automatically.

import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";

const here = path.dirname(fileURLToPath(import.meta.url));
const webRoot = path.resolve(here, "..");
const lessonsDir = path.resolve(webRoot, "..", "lessons");
const outFile = path.join(webRoot, "lib", "lessons-generated.ts");

if (!existsSync(lessonsDir)) {
  console.error(`generate-lessons: lessons dir not found at ${lessonsDir}`);
  process.exit(1);
}

const files = (await readdir(lessonsDir)).filter((f) => f.endsWith(".yml"));
const lessons = [];
for (const f of files) {
  const raw = await readFile(path.join(lessonsDir, f), "utf8");
  const parsed = yaml.load(raw);
  if (!parsed || typeof parsed !== "object") continue;
  if (!parsed.id || !parsed.language) {
    console.warn(`generate-lessons: skipping ${f}, missing id/language`);
    continue;
  }
  lessons.push(parsed);
}

lessons.sort((a, b) => {
  if (a.module_number !== b.module_number) return a.module_number - b.module_number;
  return a.language.localeCompare(b.language);
});

await mkdir(path.dirname(outFile), { recursive: true });
await writeFile(
  outFile,
  `// AUTO-GENERATED by scripts/generate-lessons.mjs at build time.
// Source: ../lessons/*.yml. Do not edit by hand.

import type { Lesson } from "./lessons";

export const LESSONS: Lesson[] = ${JSON.stringify(lessons, null, 2)};
`,
  "utf8",
);

console.log(`generate-lessons: wrote ${lessons.length} lessons to ${path.relative(webRoot, outFile)}`);
