// Code generated by shared/api/codegen.mjs. DO NOT EDIT.
//
// Source: shared/api/{schemas,events,errors}.ts via zod-to-json-schema.
// Regenerate with: pnpm codegen:api (from repo root).
//
// JSON tags mirror the wire format exactly. Optional and nullable fields use
// pointer types with omitempty so (nil) round-trips as the field missing from
// the wire.

package apitypes

import (
	"encoding/json"
)

var _ = json.Marshal

type MintIdentityRequest struct {
	UUID       *string `json:"uuid,omitempty"`
	DeviceHint *string `json:"device_hint,omitempty"`
	Lang       string  `json:"lang"`
}

type MintIdentityResponse struct {
	UUID   string `json:"uuid"`
	Cookie string `json:"cookie"`
}

type RequestMagicLinkRequest struct {
	Email         string  `json:"email"`
	AnonymousUUID *string `json:"anonymous_uuid,omitempty"`
	Lang          string  `json:"lang"`
}

type RequestMagicLinkResponse struct {
	Ok               bool `json:"ok"`
	ExpiresInSeconds int  `json:"expires_in_seconds"`
}

type ClaimAccountRequest struct {
	MagicLinkToken string  `json:"magic_link_token"`
	AnonymousUUID  *string `json:"anonymous_uuid,omitempty"`
}

type ClaimAccountResponse struct {
	UUID         string `json:"uuid"`
	Email        string `json:"email"`
	SessionToken string `json:"session_token"`
}

type MeResponse struct {
	UUID           string  `json:"uuid"`
	Email          *string `json:"email,omitempty"`
	Lang           string  `json:"lang"`
	Department     *string `json:"department,omitempty"`
	Name           *string `json:"name,omitempty"`
	StreakDays     int     `json:"streak_days"`
	TotalXP        int     `json:"total_xp"`
	GraceTokens    int     `json:"grace_tokens"`
	HapticsEnabled bool    `json:"haptics_enabled"`
	PushEnabled    bool    `json:"push_enabled"`
	CreatedAt      string  `json:"created_at"`
	ClaimedAt      *string `json:"claimed_at,omitempty"`
}

type PatchMeRequest struct {
	Lang           *string `json:"lang,omitempty"`
	Department     *string `json:"department,omitempty"`
	Name           *string `json:"name,omitempty"`
	HapticsEnabled *bool   `json:"haptics_enabled,omitempty"`
	PushEnabled    *bool   `json:"push_enabled,omitempty"`
}

type PatchMeResponse struct {
	UUID           string  `json:"uuid"`
	Email          *string `json:"email,omitempty"`
	Lang           string  `json:"lang"`
	Department     *string `json:"department,omitempty"`
	Name           *string `json:"name,omitempty"`
	StreakDays     int     `json:"streak_days"`
	TotalXP        int     `json:"total_xp"`
	GraceTokens    int     `json:"grace_tokens"`
	HapticsEnabled bool    `json:"haptics_enabled"`
	PushEnabled    bool    `json:"push_enabled"`
	CreatedAt      string  `json:"created_at"`
	ClaimedAt      *string `json:"claimed_at,omitempty"`
}

type ModuleProgress struct {
	CompletedSteps []string `json:"completed_steps"`
	PausedAt       *string  `json:"paused_at,omitempty"`
	XPEarned       int      `json:"xp_earned"`
}

type ProgressState struct {
	Modules        map[string]ModuleProgress `json:"modules"`
	StreakDays     int                       `json:"streak_days"`
	GraceTokens    int                       `json:"grace_tokens"`
	LastVisited    string                    `json:"last_visited"`
	SeenCoachmarks []string                  `json:"seen_coachmarks"`
	UpdatedAt      string                    `json:"updated_at"`
}

type ProgressSyncRequest struct {
	UUID  string        `json:"uuid"`
	State ProgressState `json:"state"`
}

type ProgressSyncResponse struct {
	State           ProgressState `json:"state"`
	ServerUpdatedAt string        `json:"server_updated_at"`
}

type LessonSummary struct {
	ID               string  `json:"id"`
	ModuleNumber     int     `json:"module_number"`
	Language         string  `json:"language"`
	Title            string  `json:"title"`
	Subtitle         *string `json:"subtitle,omitempty"`
	EstimatedMinutes *int    `json:"estimated_minutes,omitempty"`
}

type ListLessonsResponse struct {
	Lessons []LessonSummary `json:"lessons"`
}

type CreateSessionRequest struct {
	LessonID string `json:"lesson_id"`
	Lang     string `json:"lang"`
	Warm     *bool  `json:"warm,omitempty"`
}

type CreateSessionResponse struct {
	SessionID          string `json:"session_id"`
	VMIP               string `json:"vm_ip"`
	PTYWSURL           string `json:"pty_ws_url"`
	WizardWSURL        string `json:"wizard_ws_url"`
	PreviewURLTemplate string `json:"preview_url_template"`
}

type HeartbeatResponse struct {
	SessionID   string `json:"session_id"`
	VMIP        string `json:"vm_ip"`
	Alive       bool   `json:"alive"`
	ClaudeBusy  bool   `json:"claude_busy"`
	LastEventAt string `json:"last_event_at"`
	AgeSeconds  int    `json:"age_seconds"`
}

type TranscriptResponse struct {
	SessionID string            `json:"session_id"`
	Events    []json.RawMessage `json:"events"`
}

type SubmitPromptRequest struct {
	Text     string `json:"text"`
	ClientTS string `json:"client_ts"`
}

type SubmitPromptResponse struct {
	Ok     bool   `json:"ok"`
	TurnID string `json:"turn_id"`
}

type AttachImageResponse struct {
	InboxPath string `json:"inbox_path"`
}

type PublicProfileResponseModulesCompletedItem struct {
	LessonID    string   `json:"lesson_id"`
	Title       string   `json:"title"`
	CompletedAt string   `json:"completed_at"`
	Takeaways   []string `json:"takeaways"`
}

type PublicProfileResponse struct {
	UUID             string                                      `json:"uuid"`
	Name             *string                                     `json:"name,omitempty"`
	Department       *string                                     `json:"department,omitempty"`
	Lang             string                                      `json:"lang"`
	StreakDays       int                                         `json:"streak_days"`
	TotalXP          int                                         `json:"total_xp"`
	ModulesCompleted []PublicProfileResponseModulesCompletedItem `json:"modules_completed"`
}

type PublicCertificateResponse struct {
	ID          string   `json:"id"`
	UUID        string   `json:"uuid"`
	Name        *string  `json:"name,omitempty"`
	Department  *string  `json:"department,omitempty"`
	Lang        string   `json:"lang"`
	CompletedAt string   `json:"completed_at"`
	Signature   string   `json:"signature"`
	Modules     []string `json:"modules"`
}

type CapstoneValidateRequest struct {
	Prompt    string  `json:"prompt"`
	Lang      *string `json:"lang,omitempty"`
	TopicHint *string `json:"topic_hint,omitempty"`
}

type CapstoneValidateResponse struct {
	Ok     bool    `json:"ok"`
	Reason *string `json:"reason,omitempty"`
}

type CapstoneBuildRequest struct {
	Prompt string  `json:"prompt"`
	Lang   *string `json:"lang,omitempty"`
}

type CapstoneBuildResponse struct {
	SessionID          string `json:"session_id"`
	VMIP               string `json:"vm_ip"`
	WizardWSURL        string `json:"wizard_ws_url"`
	PreviewURLTemplate string `json:"preview_url_template"`
	TurnID             string `json:"turn_id"`
}

type ApiError struct {
	Code              string `json:"code"`
	Message           string `json:"message"`
	RetryAfterSeconds *int   `json:"retry_after_seconds,omitempty"`
	QueuePosition     *int   `json:"queue_position,omitempty"`
	RequestID         string `json:"request_id"`
}

type SessionStartedEvent struct {
	TS        string `json:"ts"`
	Type      string `json:"type"`
	SessionID string `json:"session_id"`
	LessonID  string `json:"lesson_id"`
}

type VmBootingEvent struct {
	TS    string `json:"ts"`
	Type  string `json:"type"`
	Stage string `json:"stage"`
}

type VmReadyEvent struct {
	TS   string `json:"ts"`
	Type string `json:"type"`
}

type AgentOnlineEvent struct {
	TS   string `json:"ts"`
	Type string `json:"type"`
}

type ProcessStartedEvent struct {
	TS   string `json:"ts"`
	Type string `json:"type"`
	Name string `json:"name"`
}

type PortListeningEvent struct {
	TS   string `json:"ts"`
	Type string `json:"type"`
	Port int    `json:"port"`
}

type ClaudePromptSentEvent struct {
	TS             string  `json:"ts"`
	Type           string  `json:"type"`
	Text           string  `json:"text"`
	Length         int     `json:"length"`
	LocaleDetected *string `json:"locale_detected,omitempty"`
}

type ClaudeToolCallEvent struct {
	TS           string            `json:"ts"`
	Type         string            `json:"type"`
	Tool         string            `json:"tool"`
	Args         map[string]string `json:"args"`
	Path         *string           `json:"path,omitempty"`
	Command      *string           `json:"command,omitempty"`
	SubagentType *string           `json:"subagent_type,omitempty"`
	CallID       string            `json:"call_id"`
}

type ClaudeToolResultEvent struct {
	TS      string  `json:"ts"`
	Type    string  `json:"type"`
	CallID  string  `json:"call_id"`
	Ok      bool    `json:"ok"`
	Summary *string `json:"summary,omitempty"`
}

type ClaudeSlashCommandEvent struct {
	TS      string  `json:"ts"`
	Type    string  `json:"type"`
	Command string  `json:"command"`
	Args    *string `json:"args,omitempty"`
}

type ClaudeMessageEvent struct {
	TS         string `json:"ts"`
	Type       string `json:"type"`
	Role       string `json:"role"`
	Text       string `json:"text"`
	DurationMs *int   `json:"duration_ms,omitempty"`
	TurnID     string `json:"turn_id"`
}

type ClaudeBusyEvent struct {
	TS   string `json:"ts"`
	Type string `json:"type"`
	Busy bool   `json:"busy"`
}

type ClaudeThinkingEvent struct {
	TS         string `json:"ts"`
	Type       string `json:"type"`
	CharsSoFar int    `json:"chars_so_far"`
}

type ClaudeTokenStreamedEvent struct {
	TS         string `json:"ts"`
	Type       string `json:"type"`
	TurnID     string `json:"turn_id"`
	Delta      string `json:"delta"`
	TotalChars int    `json:"total_chars"`
}

type FileExistsEvent struct {
	TS   string `json:"ts"`
	Type string `json:"type"`
	Path string `json:"path"`
}

type FileContentsRegexEvent struct {
	TS      string `json:"ts"`
	Type    string `json:"type"`
	Path    string `json:"path"`
	RegexID string `json:"regex_id"`
	Snippet string `json:"snippet"`
}

type StepSatisfiedEvent struct {
	TS       string          `json:"ts"`
	Type     string          `json:"type"`
	StepID   string          `json:"step_id"`
	LessonID string          `json:"lesson_id"`
	Evidence json.RawMessage `json:"evidence,omitempty"`
}

type SessionErrorEvent struct {
	TS      string `json:"ts"`
	Type    string `json:"type"`
	Code    string `json:"code"`
	Message string `json:"message"`
}

type SessionClosedEvent struct {
	TS     string `json:"ts"`
	Type   string `json:"type"`
	Reason string `json:"reason"`
}

type FilesSnapshotFile struct {
	Path      string `json:"path"`
	Content   string `json:"content"`
	SizeBytes int    `json:"size_bytes"`
}

type FilesSnapshotEvent struct {
	TS    string              `json:"ts"`
	Type  string              `json:"type"`
	Root  string              `json:"root"`
	Files []FilesSnapshotFile `json:"files"`
}

// WsEventEnvelope is the minimal shape needed to discriminate a WsEvent by
// type before full decode. WsEventType lists every known discriminator;
// mirrors the TS discriminated union in shared/api/events.ts.
type WsEventEnvelope struct {
	Type string `json:"type"`
	Ts   string `json:"ts"`
}

type WsEventType string

const (
	WsEventSessionStarted     WsEventType = "session_started"
	WsEventVmBooting          WsEventType = "vm_booting"
	WsEventVmReady            WsEventType = "vm_ready"
	WsEventAgentOnline        WsEventType = "agent_online"
	WsEventProcessStarted     WsEventType = "process_started"
	WsEventPortListening      WsEventType = "port_listening"
	WsEventClaudePromptSent   WsEventType = "claude_prompt_sent"
	WsEventClaudeToolCall     WsEventType = "claude_tool_call"
	WsEventClaudeToolResult   WsEventType = "claude_tool_result"
	WsEventClaudeSlashCommand WsEventType = "claude_slash_command"
	WsEventClaudeMessage      WsEventType = "claude_message"
	WsEventClaudeBusy         WsEventType = "claude_busy"
	WsEventClaudeThinking     WsEventType = "claude_thinking"
	WsEventClaudeTokenStream  WsEventType = "claude_token_streamed"
	WsEventFileExists         WsEventType = "file_exists"
	WsEventFileContentsRegex  WsEventType = "file_contents_regex"
	WsEventStepSatisfied      WsEventType = "step_satisfied"
	WsEventSessionError       WsEventType = "session_error"
	WsEventSessionClosed      WsEventType = "session_closed"
	WsEventFilesSnapshot      WsEventType = "files_snapshot"
)

// ApiErrorCode enumerates every known control-plane error code. Mirrors the
// ApiErrorCode enum in shared/api/errors.ts.
type ApiErrorCode string

const (
	ApiErrorCapacityFull     ApiErrorCode = "capacity_full"
	ApiErrorAuthRequired     ApiErrorCode = "auth_required"
	ApiErrorAuthInvalid      ApiErrorCode = "auth_invalid"
	ApiErrorMagicLinkExpired ApiErrorCode = "magic_link_expired"
	ApiErrorVMLaunchFailed   ApiErrorCode = "vm_launch_failed"
	ApiErrorVMNotFound       ApiErrorCode = "vm_not_found"
	ApiErrorSessionReaped    ApiErrorCode = "session_reaped"
	ApiErrorBadRequest       ApiErrorCode = "bad_request"
	ApiErrorNotFound         ApiErrorCode = "not_found"
	ApiErrorRateLimited      ApiErrorCode = "rate_limited"
	ApiErrorInternal         ApiErrorCode = "internal"
)
