#!/usr/bin/env node
// Generate shared/voice/types.ts from shared/voice/es.json.
//
// es.json is canonical; en.json must mirror its key tree. The generated
// types.ts exports a VoiceKey string-literal union covering every leaf path
// (dot-joined), plus a typed `t(lang, key, params?)` helper.
//
// The generated file also contains an explicit structural type (Voice) built
// from the es.json shape. en.json is imported and annotated with that type,
// so a missing key in en.json fails typecheck.
//
// Run: `pnpm codegen:voice`.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const es = JSON.parse(readFileSync(join(here, "es.json"), "utf8"));

function collectLeaves(obj, prefix, out) {
  for (const [k, v] of Object.entries(obj)) {
    const path = prefix ? `${prefix}.${k}` : k;
    if (v && typeof v === "object" && !Array.isArray(v)) {
      collectLeaves(v, path, out);
    } else {
      out.push(path);
    }
  }
  return out;
}

function emitShape(obj, indent) {
  const lines = ["{"];
  const pad = "  ".repeat(indent + 1);
  for (const [k, v] of Object.entries(obj)) {
    const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
    if (v && typeof v === "object" && !Array.isArray(v)) {
      lines.push(`${pad}${key}: ${emitShape(v, indent + 1)};`);
    } else {
      lines.push(`${pad}${key}: string;`);
    }
  }
  lines.push(`${"  ".repeat(indent)}}`);
  return lines.join("\n");
}

const keys = collectLeaves(es, "", []).sort();
const shape = emitShape(es, 0);

const header = `// AUTOGENERATED by shared/voice/codegen.mjs. Do not edit by hand.
// Regenerate: \`pnpm codegen:voice\`.
// Source: shared/voice/es.json (canonical). shared/voice/en.json must mirror
// this exact key tree or this file fails typecheck.

import esJson from "./es.json" with { type: "json" };
import enJson from "./en.json" with { type: "json" };

export type Lang = "es" | "en";

`;

const shapeDecl = `export type Voice = ${shape};\n\n`;

const unionLines = keys.map((k) => `  | ${JSON.stringify(k)}`).join("\n");
const voiceKey = `export type VoiceKey =\n${unionLines};\n\n`;

const body = `// The structural check: enJson must be assignable to Voice (derived from
// esJson). A missing key or wrong type in en.json breaks this line.
const _esCheck: Voice = esJson;
const _enCheck: Voice = enJson;
void _esCheck;
void _enCheck;

const tables: Record<Lang, Voice> = { es: esJson, en: enJson };

function resolve(table: Voice, key: VoiceKey): string | undefined {
  const parts = key.split(".");
  let cur: unknown = table;
  for (const p of parts) {
    if (cur !== null && typeof cur === "object" && p in (cur as Record<string, unknown>)) {
      cur = (cur as Record<string, unknown>)[p];
    } else {
      return undefined;
    }
  }
  return typeof cur === "string" ? cur : undefined;
}

export function t(
  lang: Lang,
  key: VoiceKey,
  params?: Record<string, string | number>,
): string {
  let value = resolve(tables[lang], key);
  if (value === undefined) {
    // Fallback to canonical Spanish, then the key itself.
    value = resolve(tables.es, key) ?? key;
  }
  if (!params) return value;
  return value.replace(/\\{(\\w+)\\}/g, (_match, name: string) =>
    params[name] !== undefined ? String(params[name]) : \`{\${name}}\`,
  );
}

export const voiceKeys: readonly VoiceKey[] = ${JSON.stringify(keys, null, 2)} as const;
`;

const output = header + shapeDecl + voiceKey + body;
writeFileSync(join(here, "types.ts"), output, "utf8");
console.log(`shared/voice/types.ts regenerated (${keys.length} keys).`);
