// AUTOGENERATED by shared/voice/codegen.mjs. Do not edit by hand.
// Regenerate: `pnpm codegen:voice`.
// Source: shared/voice/es.json (canonical). shared/voice/en.json must mirror
// this exact key tree or this file fails typecheck.

import esJson from "./es.json" with { type: "json" };
import enJson from "./en.json" with { type: "json" };

export type Lang = "es" | "en";

export type Voice = {
  welcome: {
    title: string;
    subtitle: string;
    cta: string;
  };
  auth: {
    magic_link: {
      title: string;
      subtitle: string;
      placeholder: string;
      cta: string;
      sent_title: string;
      sent_subtitle: string;
      error_rate_limited: string;
      error_invalid_email: string;
      error_generic: string;
    };
    claim: {
      welcome_back: string;
      progress_migrated: string;
    };
    skip: string;
  };
  role_pick: {
    title: string;
    subtitle: string;
    skip: string;
    departments: {
      ventas: string;
      marketing: string;
      tecnologia: string;
      producto: string;
      finanzas: string;
      rrhh: string;
      legal: string;
      estrategia: string;
    };
    taglines: {
      ventas: string;
      marketing: string;
      tecnologia: string;
      producto: string;
      finanzas: string;
      rrhh: string;
      legal: string;
      estrategia: string;
    };
  };
  path: {
    header: string;
    streak_singular: string;
    streak_plural: string;
    streak_zero: string;
    locked_hint: string;
    tap_to_resume: string;
  };
  lesson: {
    loading: {
      booting: string;
      booting_sub: string;
      starting_claude: string;
      almost_ready: string;
    };
    context: {
      reading_hint: string;
    };
    composer: {
      placeholder: string;
      placeholder_voice: string;
      send: string;
      dictating: string;
      dictation_done: string;
      camera_hint: string;
      busy: string;
      sending: string;
    };
    tool_cards: {
      Read: string;
      Write: string;
      Edit: string;
      Bash: string;
      Glob: string;
      Grep: string;
      Task: string;
      WebFetch: string;
      WebSearch: string;
      SlashCommand: string;
      Other: string;
    };
    moment: {
      xp_earned: string;
      streak_tick: string;
      continue: string;
      break_here: string;
    };
    error: {
      capacity: string;
      launch: string;
      auth: string;
      unknown: string;
      retry: string;
      panic: string;
    };
    safe_to_break: string;
    reset_confirm: string;
    reset_cta: string;
  };
  return: {
    short_title: string;
    short_cta: string;
    medium_title: string;
    medium_sub: string;
    medium_review: string;
    medium_continue: string;
    long_title: string;
    long_sub: string;
    long_cta: string;
    grace_used: string;
    streak_broken: string;
  };
  settings: {
    title: string;
    done: string;
    section_account: string;
    section_preferences: string;
    section_data: string;
    lang: string;
    lang_es: string;
    lang_en: string;
    department: string;
    haptics: string;
    push: string;
    data_export: string;
    data_delete: string;
    sign_out: string;
  };
  certificate: {
    issued_to: string;
    completed: string;
    on_date: string;
    verify_cta: string;
    add_to_linkedin: string;
    download_pdf: string;
    share: string;
  };
  share: {
    title: string;
    body_profile: string;
    body_module: string;
    body_certificate: string;
  };
  push: {
    streak_at_risk: string;
    session_resume: string;
    tomorrow_first_prompt: string;
  };
  error: {
    capacity: string;
    launch: string;
    unknown: string;
    auth: string;
  };
  taller: {
    phase_title: string;
    phase_subtitle: string;
    pillars: {
      comandos: {
        title: string;
        subtitle: string;
        label: string;
        intro: string;
      };
      context: {
        title: string;
        subtitle: string;
        label: string;
        intro: string;
      };
      prompting: {
        title: string;
        subtitle: string;
        label: string;
        intro: string;
      };
    };
    mascado_level: {
      high: string;
      medium: string;
      low: string;
    };
    step_feedback: {
      copied_prompt: string;
      typed_own: string;
      slash_done: string;
      read_detected: string;
      tool_call_running: string;
      window_checked: string;
      window_saved: string;
    };
    pillar_complete: {
      comandos: string;
      context: string;
      prompting: string;
    };
    phase_complete: {
      title: string;
      subtitle: string;
      cta: string;
    };
  };
};

export type VoiceKey =
  | "auth.claim.progress_migrated"
  | "auth.claim.welcome_back"
  | "auth.magic_link.cta"
  | "auth.magic_link.error_generic"
  | "auth.magic_link.error_invalid_email"
  | "auth.magic_link.error_rate_limited"
  | "auth.magic_link.placeholder"
  | "auth.magic_link.sent_subtitle"
  | "auth.magic_link.sent_title"
  | "auth.magic_link.subtitle"
  | "auth.magic_link.title"
  | "auth.skip"
  | "certificate.add_to_linkedin"
  | "certificate.completed"
  | "certificate.download_pdf"
  | "certificate.issued_to"
  | "certificate.on_date"
  | "certificate.share"
  | "certificate.verify_cta"
  | "error.auth"
  | "error.capacity"
  | "error.launch"
  | "error.unknown"
  | "lesson.composer.busy"
  | "lesson.composer.camera_hint"
  | "lesson.composer.dictating"
  | "lesson.composer.dictation_done"
  | "lesson.composer.placeholder"
  | "lesson.composer.placeholder_voice"
  | "lesson.composer.send"
  | "lesson.composer.sending"
  | "lesson.context.reading_hint"
  | "lesson.error.auth"
  | "lesson.error.capacity"
  | "lesson.error.launch"
  | "lesson.error.panic"
  | "lesson.error.retry"
  | "lesson.error.unknown"
  | "lesson.loading.almost_ready"
  | "lesson.loading.booting"
  | "lesson.loading.booting_sub"
  | "lesson.loading.starting_claude"
  | "lesson.moment.break_here"
  | "lesson.moment.continue"
  | "lesson.moment.streak_tick"
  | "lesson.moment.xp_earned"
  | "lesson.reset_confirm"
  | "lesson.reset_cta"
  | "lesson.safe_to_break"
  | "lesson.tool_cards.Bash"
  | "lesson.tool_cards.Edit"
  | "lesson.tool_cards.Glob"
  | "lesson.tool_cards.Grep"
  | "lesson.tool_cards.Other"
  | "lesson.tool_cards.Read"
  | "lesson.tool_cards.SlashCommand"
  | "lesson.tool_cards.Task"
  | "lesson.tool_cards.WebFetch"
  | "lesson.tool_cards.WebSearch"
  | "lesson.tool_cards.Write"
  | "path.header"
  | "path.locked_hint"
  | "path.streak_plural"
  | "path.streak_singular"
  | "path.streak_zero"
  | "path.tap_to_resume"
  | "push.session_resume"
  | "push.streak_at_risk"
  | "push.tomorrow_first_prompt"
  | "return.grace_used"
  | "return.long_cta"
  | "return.long_sub"
  | "return.long_title"
  | "return.medium_continue"
  | "return.medium_review"
  | "return.medium_sub"
  | "return.medium_title"
  | "return.short_cta"
  | "return.short_title"
  | "return.streak_broken"
  | "role_pick.departments.estrategia"
  | "role_pick.departments.finanzas"
  | "role_pick.departments.legal"
  | "role_pick.departments.marketing"
  | "role_pick.departments.producto"
  | "role_pick.departments.rrhh"
  | "role_pick.departments.tecnologia"
  | "role_pick.departments.ventas"
  | "role_pick.skip"
  | "role_pick.subtitle"
  | "role_pick.taglines.estrategia"
  | "role_pick.taglines.finanzas"
  | "role_pick.taglines.legal"
  | "role_pick.taglines.marketing"
  | "role_pick.taglines.producto"
  | "role_pick.taglines.rrhh"
  | "role_pick.taglines.tecnologia"
  | "role_pick.taglines.ventas"
  | "role_pick.title"
  | "settings.data_delete"
  | "settings.data_export"
  | "settings.department"
  | "settings.done"
  | "settings.haptics"
  | "settings.lang"
  | "settings.lang_en"
  | "settings.lang_es"
  | "settings.push"
  | "settings.section_account"
  | "settings.section_data"
  | "settings.section_preferences"
  | "settings.sign_out"
  | "settings.title"
  | "share.body_certificate"
  | "share.body_module"
  | "share.body_profile"
  | "share.title"
  | "taller.mascado_level.high"
  | "taller.mascado_level.low"
  | "taller.mascado_level.medium"
  | "taller.phase_complete.cta"
  | "taller.phase_complete.subtitle"
  | "taller.phase_complete.title"
  | "taller.phase_subtitle"
  | "taller.phase_title"
  | "taller.pillar_complete.comandos"
  | "taller.pillar_complete.context"
  | "taller.pillar_complete.prompting"
  | "taller.pillars.comandos.intro"
  | "taller.pillars.comandos.label"
  | "taller.pillars.comandos.subtitle"
  | "taller.pillars.comandos.title"
  | "taller.pillars.context.intro"
  | "taller.pillars.context.label"
  | "taller.pillars.context.subtitle"
  | "taller.pillars.context.title"
  | "taller.pillars.prompting.intro"
  | "taller.pillars.prompting.label"
  | "taller.pillars.prompting.subtitle"
  | "taller.pillars.prompting.title"
  | "taller.step_feedback.copied_prompt"
  | "taller.step_feedback.read_detected"
  | "taller.step_feedback.slash_done"
  | "taller.step_feedback.tool_call_running"
  | "taller.step_feedback.typed_own"
  | "taller.step_feedback.window_checked"
  | "taller.step_feedback.window_saved"
  | "welcome.cta"
  | "welcome.subtitle"
  | "welcome.title";

// The structural check: enJson must be assignable to Voice (derived from
// esJson). A missing key or wrong type in en.json breaks this line.
const _esCheck: Voice = esJson;
const _enCheck: Voice = enJson;
void _esCheck;
void _enCheck;

const tables: Record<Lang, Voice> = { es: esJson, en: enJson };

function resolve(table: Voice, key: VoiceKey): string | undefined {
  const parts = key.split(".");
  let cur: unknown = table;
  for (const p of parts) {
    if (cur !== null && typeof cur === "object" && p in (cur as Record<string, unknown>)) {
      cur = (cur as Record<string, unknown>)[p];
    } else {
      return undefined;
    }
  }
  return typeof cur === "string" ? cur : undefined;
}

export function t(
  lang: Lang,
  key: VoiceKey,
  params?: Record<string, string | number>,
): string {
  let value = resolve(tables[lang], key);
  if (value === undefined) {
    // Fallback to canonical Spanish, then the key itself.
    value = resolve(tables.es, key) ?? key;
  }
  if (!params) return value;
  return value.replace(/\{(\w+)\}/g, (_match, name: string) =>
    params[name] !== undefined ? String(params[name]) : `{${name}}`,
  );
}

export const voiceKeys: readonly VoiceKey[] = [
  "auth.claim.progress_migrated",
  "auth.claim.welcome_back",
  "auth.magic_link.cta",
  "auth.magic_link.error_generic",
  "auth.magic_link.error_invalid_email",
  "auth.magic_link.error_rate_limited",
  "auth.magic_link.placeholder",
  "auth.magic_link.sent_subtitle",
  "auth.magic_link.sent_title",
  "auth.magic_link.subtitle",
  "auth.magic_link.title",
  "auth.skip",
  "certificate.add_to_linkedin",
  "certificate.completed",
  "certificate.download_pdf",
  "certificate.issued_to",
  "certificate.on_date",
  "certificate.share",
  "certificate.verify_cta",
  "error.auth",
  "error.capacity",
  "error.launch",
  "error.unknown",
  "lesson.composer.busy",
  "lesson.composer.camera_hint",
  "lesson.composer.dictating",
  "lesson.composer.dictation_done",
  "lesson.composer.placeholder",
  "lesson.composer.placeholder_voice",
  "lesson.composer.send",
  "lesson.composer.sending",
  "lesson.context.reading_hint",
  "lesson.error.auth",
  "lesson.error.capacity",
  "lesson.error.launch",
  "lesson.error.panic",
  "lesson.error.retry",
  "lesson.error.unknown",
  "lesson.loading.almost_ready",
  "lesson.loading.booting",
  "lesson.loading.booting_sub",
  "lesson.loading.starting_claude",
  "lesson.moment.break_here",
  "lesson.moment.continue",
  "lesson.moment.streak_tick",
  "lesson.moment.xp_earned",
  "lesson.reset_confirm",
  "lesson.reset_cta",
  "lesson.safe_to_break",
  "lesson.tool_cards.Bash",
  "lesson.tool_cards.Edit",
  "lesson.tool_cards.Glob",
  "lesson.tool_cards.Grep",
  "lesson.tool_cards.Other",
  "lesson.tool_cards.Read",
  "lesson.tool_cards.SlashCommand",
  "lesson.tool_cards.Task",
  "lesson.tool_cards.WebFetch",
  "lesson.tool_cards.WebSearch",
  "lesson.tool_cards.Write",
  "path.header",
  "path.locked_hint",
  "path.streak_plural",
  "path.streak_singular",
  "path.streak_zero",
  "path.tap_to_resume",
  "push.session_resume",
  "push.streak_at_risk",
  "push.tomorrow_first_prompt",
  "return.grace_used",
  "return.long_cta",
  "return.long_sub",
  "return.long_title",
  "return.medium_continue",
  "return.medium_review",
  "return.medium_sub",
  "return.medium_title",
  "return.short_cta",
  "return.short_title",
  "return.streak_broken",
  "role_pick.departments.estrategia",
  "role_pick.departments.finanzas",
  "role_pick.departments.legal",
  "role_pick.departments.marketing",
  "role_pick.departments.producto",
  "role_pick.departments.rrhh",
  "role_pick.departments.tecnologia",
  "role_pick.departments.ventas",
  "role_pick.skip",
  "role_pick.subtitle",
  "role_pick.taglines.estrategia",
  "role_pick.taglines.finanzas",
  "role_pick.taglines.legal",
  "role_pick.taglines.marketing",
  "role_pick.taglines.producto",
  "role_pick.taglines.rrhh",
  "role_pick.taglines.tecnologia",
  "role_pick.taglines.ventas",
  "role_pick.title",
  "settings.data_delete",
  "settings.data_export",
  "settings.department",
  "settings.done",
  "settings.haptics",
  "settings.lang",
  "settings.lang_en",
  "settings.lang_es",
  "settings.push",
  "settings.section_account",
  "settings.section_data",
  "settings.section_preferences",
  "settings.sign_out",
  "settings.title",
  "share.body_certificate",
  "share.body_module",
  "share.body_profile",
  "share.title",
  "taller.mascado_level.high",
  "taller.mascado_level.low",
  "taller.mascado_level.medium",
  "taller.phase_complete.cta",
  "taller.phase_complete.subtitle",
  "taller.phase_complete.title",
  "taller.phase_subtitle",
  "taller.phase_title",
  "taller.pillar_complete.comandos",
  "taller.pillar_complete.context",
  "taller.pillar_complete.prompting",
  "taller.pillars.comandos.intro",
  "taller.pillars.comandos.label",
  "taller.pillars.comandos.subtitle",
  "taller.pillars.comandos.title",
  "taller.pillars.context.intro",
  "taller.pillars.context.label",
  "taller.pillars.context.subtitle",
  "taller.pillars.context.title",
  "taller.pillars.prompting.intro",
  "taller.pillars.prompting.label",
  "taller.pillars.prompting.subtitle",
  "taller.pillars.prompting.title",
  "taller.step_feedback.copied_prompt",
  "taller.step_feedback.read_detected",
  "taller.step_feedback.slash_done",
  "taller.step_feedback.tool_call_running",
  "taller.step_feedback.typed_own",
  "taller.step_feedback.window_checked",
  "taller.step_feedback.window_saved",
  "welcome.cta",
  "welcome.subtitle",
  "welcome.title"
] as const;
